version: "3.9"

services:
  dispatcher:
    image: fteychene/cloud-cadavre-exquis-dispatcher-bis:1.0-SNAPSHOT
    ports:
      - 8080:8080
    environment:
      SUBJECT_URL: "http://providers-subject:8080"
      VERB_URL: "http://providers-verb:8080"
      ADJECTIVE_URL: "http://providers-adj:8080"
  
  providers-subject:
    image: fteychene/cloud-cadavre-exquis-provider-bis:1.0-SNAPSHOT
    environment:
      WORD_TYPE: SUBJECT
  
  providers-verb:
    image: fteychene/cloud-cadavre-exquis-provider-bis:1.0-SNAPSHOT
    environment:
      WORD_TYPE: VERB
  
  providers-adj:
    image: fteychene/cloud-cadavre-exquis-provider-bis:1.0-SNAPSHOT
    environment:
      WORD_TYPE: ADJECTIVE