---
- name: Getting kubeconfig
  hosts: "{{ node | default('all') }}"
  tasks:
    - name: Copy kubeconfig from server to host
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ./
      become: true
